some changes

diff --git a/assertZM b/assertZM
--- a/assertZM
+++ b/assertZM
@@ -47,6 +47,14 @@ then
 	echo "$(date +%h\ %d\ %H:%M:%S) assertZM: INF zoneminder was not running." >> /var/log/syslog
 	exit 2
 fi
+tail /var/log/syslog  | grep -i Buffer
+if [ "$?" -eq 0 ]
+then
+	sudo service zoneminder stop
+	logger "assertZM: WAR zoneminder cannot be fixed, try to un+replug the camera"
+	pbme "assertZM: ERROR try to un+replug the cam"
+	exit 4
+fi
 echo "$(date +%h\ %d\ %H:%M:%S) assertZM: all good :)" >> /var/log/syslog
 echo "assertZM: all good :)"
 exit 0
